[PHP]
memory_limit = 512M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 300
max_input_time = 300

; DEV: Tampilkan error ke browser/response agar mudah dibaca
expose_php = On
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /dev/stderr
date.timezone = Asia/Jakarta

; Session Dev (Pakai DB 0 biar beda sama prod kalau misal connect ke redis yg sama)
session.save_handler = redis
session.save_path = "tcp://redis:6379?database=0"

[opcache]
; DEV: MATIKAN TOTAL.
; Ini kunci agar tidak perlu "Hard Reset".
; Setiap save file, PHP baca ulang dari disk.
opcache.enable = 0
opcache.enable_cli = 0

[xdebug]
; Config Xdebug langsung disini biar Dockerfile bersih
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = VSCODE

[Exceptions]
; Sentry Integration
zend.exception_ignore_args = Off